### ISSUE TITLE
instantly crashing

### ISSUE THREAD

**Issue by jokeris111** [mdilai/Shtreeba#13]
hey, whenever I try to inject my csgo just crashes straight away, with any other injector it is working fine, I downloaded compiled version, haven't changed a bit.

**Comment by mdilai** [comment]
Could you provide more info? Ideally, can you provide a DLL which give errors? If it's your code/paste, do you compile in Release or Debug mode (afaik current version of Shtreeba have troubles with DLLs compiled by VS studio in Debug mode)? Also if you have access to code and it's compiled in Release mode without run-time checks, you may try to add "/Zc:threadSafeInit-" as this helped some people with fancy DLLs.

**Comment by jokeris111** [comment]
You are 100% right my dll is build in debug mode because I can't build it in release, I am getting some errors of code typed twice or something like that.
