### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sendekaizen** [mdilai/Shtreeba#6]
idk i followed the instructions after i release in 86x , after checking the release folder it doesnt have the EXE. and INI. only the DLL exist

**Comment by mdilai** [comment]
Be sure that you properly opened Shtreeba.sln in visual studio, see both UI and Library in projects window and you press "Build solution" instead of "Build project".

**Comment by uwuLegacy** [comment]
If you're having troubles compiling the source, download the [prebuilt binaries](https://github.com/mdilai/Shtreeba/releases/download/v2.0.0.1/Shtreeba-v2.0.0.1.zip) provided by the developer
